### PR TITLE
Add/reduce stocks with feature of viewing history

### PR DESCRIPTION
**Pull request by MrSachin7**

### CODE REVIEW

**Comment by himal28924** [comment]
image
i guees it should have been total number of lines

**Comment by himal28924** [comment]
image
Datefield : doesn't it look weird like drawn by pen , it looks cool , but somehow doesn't match the vibes ,at least for me , if possible can you make date field looks like stock one , if it is going to takes a lot of effort then you can leave it

**Comment by himal28924** [comment]
image
As you can see i only have one item its saying 9-9

**Comment by himal28924** [comment]
Can you try adding new item , will you get this error if not then its on me :

Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'props')
TypeError: Cannot read properties of undefined (reading 'props')
    at deleteToast (http://localhost:3000/static/js/bundle.js:108139:27)

**Comment by himal28924** [comment]
I think we can not add stock for future date but as of now we can do that can you fix it 
image

**Comment by himal28924** [comment]
image
Stock weight must be positive ?

**Comment by himal28924** [comment]
When you are working with item can you also fix sort  by balance

**Review by himal28924 — COMMENTED** [review]
I have left you some comment let me know if you fix it or its ok , then we can merge it Gambatte :)

**Comment by MrSachin7** [comment]
La ma uthdai xuu 🤣

**Comment by MrSachin7** [comment]
> Can you try adding new item , will you get this error if not then its on me :
> 
> Uncaught runtime errors: × ERROR Cannot read properties of undefined (reading 'props') TypeError: Cannot read properties of undefined (reading 'props') at deleteToast (http://localhost:3000/static/js/bundle.js:108139:27)

Yep fixed

**Comment by MrSachin7** [comment]
For some reason, i cant reply to the commend. Wierd

**Comment by MrSachin7** [comment]
> image
> Datefield : doesn't it look weird like drawn by pen , it looks cool , but somehow doesn't match the vibes ,at least for me , if possible can you make date field looks like stock one , if it is going to takes a lot of effort then you can leave it


Did as musch as i can

**Comment by MrSachin7** [comment]
> > image
> > Datefield : doesn't it look weird like drawn by pen , it looks cool , but somehow doesn't match the vibes ,at least for me , if possible can you make date field looks like stock one , if it is going to takes a lot of effort then you can leave it
> 
> Did as musch as i can
image

ofc i have changed it a bit

**Comment by MrSachin7** [comment]
> Stock weight must be positive ?

this seems to be frontend error

**Comment by MrSachin7** [comment]
Fixed everything 👌

**Review by himal28924 — APPROVED** [review]

**Pull request merged**
